INSERT INTO dbo.ProcessingJobs
(
	JobName,
	JobDescription,
	JobOperationMode,
	IsJobActiveFlag,
	ProcedureName,
	BackupFolderPath,
	InputFileFolderPath,
	InputFileName,
	InputFileExtension,
	InputFileSeparatorChar,
	OutputFileFolderPath,
	OutputFileName,
	OutputFileExtension,
	OutputFileSeparatorChar,
	FileExportDateTimeFlag,
	FileProcessingDateTimeFlag
	)
VALUES
(
	'CV4S001S',
	'This job executes the copy of the suitability file.',
	0,
	1,
	NULL,
	'C:\USERS\FRAZEAL\SOURCE\REPOS\PLATAFORMAEXPORTACAO\SERVER\BACKUP',
	'C:\USERS\FRAZEAL\SOURCE\REPOS\PLATAFORMAEXPORTACAO\SERVER\INPUT',
	'SUITABILITY',
	'TXT',
	NULL,
	'C:\USERS\FRAZEAL\SOURCE\REPOS\PLATAFORMAEXPORTACAO\SERVER\OUTPUT',
	'SUITABILITY',
	'CSV',
	',',
	1,
	0
)